# Generated by Django 4.0 on 2022-01-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_number',
        ),
    ]
